<VoiceWidget>:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        ToggleButton:
            id: voice_btn
            text: 'Make voice command' if self.state == 'normal' else 'Listening...'
            size_hint_y: None
            height: '48dp'
        TextInput:
            id: emul_txt
            size_hint_y: None
            height: '48dp'
        Label:
            text: root.recognized_text
            size_hint_y: None
            height: '48dp'